<?php

namespace Cocorico\CoreBundle\Entity;

/**
 * ListingSubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingSubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
